name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t <your-dockerhub-username>/nodejs-cicd-ec2-app:v1 .

      - name: Push image to DockerHub
        run: docker push <your-dockerhub-username>/nodejs-cicd-ec2-app:v1

